apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: filebeat
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
      - nodes
      - pods
      - services
      - replicationcontrollers
      - limitranges
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:6.2.3
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          args:
            - "-e"
          ports:
            - name: filebeat
              containerPort: 5066
          env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch-ingest
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: KIBANA_HOST
              value: "kibana.kube-system.svc.cluster.local"
            - name: KIBANA_PORT
              value: "5601"
          volumeMounts:
            - name: data
              mountPath: /usr/share/filebeat/data
            - name: varlog
              mountPath: /var/log
            - name: dockersock
              mountPath: /var/run/docker.sock
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              readOnly: true
              subPath: filebeat.yml
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: filebeat-config
          configMap:
            name: filebeat-config
        - name: data
          hostPath:
            path: /var/lib/filebeat
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |
    setup:
      dashboards:
        enabled: true
        index: "filebeat-*"
        retry:
          enabled: true
          interval: 5
      kibana:
        host: "${KIBANA_HOST}:${KIBANA_PORT}"
    path:
      logs: /var/log/
    output:
      elasticsearch:
        hosts: ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
    filebeat:
      config:
        prospectors:
          path: ${path.config}/prospectors.d/*.yml
          reload:
            enabled: false
        modules:
          path: ${path.config}/modules.d/*.yml
          reload:
            enabled: false
      autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  equals:
                    kubernetes.namespace: kube-system
                config:
                  - type: docker
                    containers.ids:
                      - "${data.kubernetes.container.id}"
                    exclude_lines: ["^\\s+[\\-`('.|_]"]
      prospectors:
        - type: docker
          containers.ids:
          - '*'
          processors:
          - add_docker_metadata: ~
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
        - drop_event:
            when:
              equals:
                kubernetes:
                  container:
                    name: "filebeat"
